app.persistence.type=mongo

spring.mongodb.uri=mongodb://${DB_USER:admin}:${DB_PASSWORD:password}@${DB_HOST:mongodb}:${DB_PORT:27017}/${DB_NAME:jobfinder}?authSource=admin
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
spring.data.jpa.repositories.enabled=false
spring.flyway.enabled=false