spring.application.name=JobFinder
app.ollama.model=mxbai-embed-large
app.ollama.url=http://localhost:11434
app.ollama.endpoint=/api/embed
app.qdrant.base=localhost
app.qdrant.grpc-port=6334
app.qdrant.rest-port=6333
app.qdrant.use-tls=false
app.qdrant.collection-name=job-finder
app.qdrant.embedding-dimension=1024
app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiration=3600000
app.jwt.refresh-expiration=604800000

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=jobfinder
spring.flyway.baseline-on-migrate=true

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:jobfinder}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect