DROP SCHEMA IF EXISTS jobfinder CASCADE;

CREATE SCHEMA IF NOT EXISTS jobfinder;

CREATE TYPE jobfinder.payment_frequency AS ENUM (
  'monthly',
  'weekly',
  'hourly',
  'project'
);

CREATE TYPE jobfinder.work_format AS ENUM (
  'remote',
  'office',
  'hybrid'
);

CREATE TYPE jobfinder.employment_type AS ENUM (
  'full_time',
  'part_time',
  'internship',
  'freelance'
);

CREATE TYPE jobfinder.application_status AS ENUM (
  'new',
  'invitation',
  'rejection'
);

CREATE TYPE jobfinder.education_degree AS ENUM (
  'bachelor',
  'master',
  'specialist',
  'phd'
);

CREATE TYPE jobfinder.language_level AS ENUM (
  'a1',
  'a2',
  'b1',
  'b2',
  'c1',
  'c2'
);

CREATE TABLE jobfinder.employers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text,
  address varchar,
  website_link varchar,
  email varchar,
  password_hash varchar,
  location_id bigint
);

CREATE TABLE jobfinder.applicants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  address varchar,
  email varchar,
  password_hash varchar,
  phone_number varchar,
  location_id bigint
);

CREATE TABLE jobfinder.locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city varchar,
  country varchar
);

CREATE TABLE jobfinder.vacancies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employer_id bigint,
  location_id bigint,
  salary decimal,
  payment_frequency jobfinder.payment_frequency,
  work_experience varchar,
  work_format jobfinder.work_format,
  description text,
  publication_date timestamp,
  employment_type jobfinder.employment_type,
  address varchar
);

CREATE TABLE jobfinder.applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vacancy_id bigint,
  resume_id bigint,
  date timestamp,
  status jobfinder.application_status
);

CREATE TABLE jobfinder.resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_id bigint,
  category_id bigint,
  description text,
  creation_date timestamp
);

CREATE TABLE jobfinder.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE jobfinder.educations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id bigint,
  institution varchar,
  faculty varchar,
  department varchar,
  graduation_year int,
  degree jobfinder.education_degree
);

CREATE TABLE jobfinder.experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id bigint,
  position varchar,
  start_date date,
  end_date date,
  company_name varchar,
  description text
);

CREATE TABLE jobfinder.skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE jobfinder.languages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE jobfinder.vacancy_skills (
  vacancy_id bigint,
  skill_id bigint
);

CREATE TABLE jobfinder.resume_skills (
  resume_id bigint,
  skill_id bigint
);

CREATE TABLE jobfinder.lang_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  language_id bigint,
  resume_id bigint,
  vacancy_id bigint,
  proficiency_level jobfinder.language_level
);
