CREATE TYPE jobfinder.vacancy_status AS ENUM (
    'INACTIVE',
    'ACTIVE'
);

ALTER TABLE jobfinder.vacancies
    ADD COLUMN status jobfinder.vacancy_status NOT NULL DEFAULT 'ACTIVE';

CREATE TABLE jobfinder.draft_vacancies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id bigint NOT NULL,
    version_timestamp timestamp NOT NULL,
    CONSTRAINT fk_draft_vacancies_vacancy_id
        FOREIGN KEY (vacancy_id) REFERENCES jobfinder.vacancies (id) ON DELETE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON jobfinder.draft_vacancies TO employer_role;
GRANT SELECT ON jobfinder.draft_vacancies TO applicant_role;
GRANT SELECT ON jobfinder.draft_vacancies TO guest_role;

