const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync(`${__dirname}/dashboard.html`, 'utf8');
const history = JSON.parse(fs.readFileSync(`${__dirname}/history-seed.json`, 'utf8'));
const elements = new Map();
const element = id => {
    if (!elements.has(id)) elements.set(id, {textContent: '', innerHTML: '', value: '', addEventListener() {}});
    return elements.get(id);
};
element('history-data').textContent = JSON.stringify(history);
element('window').value = '30';
element('stage').value = 'all';
const context = vm.createContext({document: {getElementById: element, addEventListener() {}}, setInterval() {}});
vm.runInContext(html.match(/<script>\n([\s\S]*?)<\/script>/)[1], context);
assert.match(element('cards').innerHTML, /706/);
assert.match(element('outcomes').innerHTML, /<svg/);
assert.match(element('duration').innerHTML, /<polyline/);
assert.equal((element('timeline').innerHTML.match(/<button/g) || []).length, 3);
vm.runInContext("selected=history[1].run;draw()", context);
assert.match(element('stages').innerHTML, /0 tests/);
assert.doesNotMatch(element('stages').innerHTML, /1 tests/);
element('stage').value = 'e2e';
vm.runInContext('draw()', context);
assert.match(element('outcomes').innerHTML, /1 passed, 0 failed/);
vm.runInContext("history=[];draw()", context);
assert.equal(element('latest').textContent, 'No runs yet');
console.log('Dashboard rendering, stage filter, run selection, skipped stages and empty state passed');
